export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization, x-api-key'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  try {
    const {
      imageBase64,
      mimeType = 'image/jpeg',
      prompt,
      apiKey: bodyApiKey
    } = req.body || {};

    const apiKey = bodyApiKey || req.headers['x-api-key'] || process.env.GEMINI_API_KEY;

    if (!imageBase64) {
      return res.status(400).json({ error: 'imageBase64 field is required for image analysis.' });
    }

    if (!apiKey) {
      return res.status(401).json({
        error: 'Gemini API Key is required. Provide it in req.body.apiKey or set GEMINI_API_KEY environment variable.'
      });
    }

    // Clean base64 string if data URL prefix is passed
    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, '');

    const defaultPrompt = `You are an expert Media Buyer and Conversion Rate Optimization (CRO) Auditor.
Analyze this ad creative, campaign screenshot, or metrics dashboard.

Please provide a structured diagnostic feedback including:
1. **Visual Hook & Design Rating**: Evaluation of attention-grabbing power, contrast, and visual hierarchy.
2. **Ad Copy / Value Proposition Analysis**: Clarity of the offer, headline impact, and call to action.
3. **Metrics & Performance Diagnosis** (if metrics are visible): CPA, CTR, ROAS, or Spend efficiency.
4. **Actionable Recommendations**: 3 concrete, step-by-step changes to improve conversion rate and ROI.

Keep the explanation clear, encouraging, and actionable (respond in Arabic if requested or if prompt is in Arabic).`;

    const userPrompt = prompt || defaultPrompt;

    const requestPayload = {
      contents: [
        {
          role: 'user',
          parts: [
            {
              inlineData: {
                mimeType: mimeType,
                data: cleanBase64
              }
            },
            {
              text: userPrompt
            }
          ]
        }
      ],
      generationConfig: {
        temperature: 0.4,
        topP: 0.9,
        maxOutputTokens: 2048
      }
    };

    let modelName = 'gemini-2.5-flash';
    let apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

    let apiResponse = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestPayload)
    });

    if (!apiResponse.ok && apiResponse.status === 404) {
      modelName = 'gemini-1.5-flash';
      apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
      apiResponse = await fetch(apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestPayload)
      });
    }

    if (!apiResponse.ok) {
      const errorData = await apiResponse.json().catch(() => ({}));
      return res.status(apiResponse.status).json({
        error: errorData.error?.message || `Gemini API error (${apiResponse.status})`,
        details: errorData
      });
    }

    const data = await apiResponse.json();
    const analysisText =
      data.candidates?.[0]?.content?.parts?.[0]?.text ||
      'No analysis text generated by Gemini.';

    return res.status(200).json({
      success: true,
      model: modelName,
      analysis: analysisText,
      usage: data.usageMetadata || null
    });
  } catch (err) {
    console.error('Error in /api/analyze:', err);
    return res.status(500).json({
      error: 'Internal server error processing image analysis request.',
      message: err.message
    });
  }
}
