export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization, x-api-key'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  try {
    const { prompt, history = [], apiKey: bodyApiKey } = req.body || {};
    const apiKey = bodyApiKey || req.headers['x-api-key'] || process.env.GEMINI_API_KEY;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required.' });
    }

    if (!apiKey) {
      return res.status(401).json({
        error: 'Gemini API Key is required. Provide it in req.body.apiKey or set GEMINI_API_KEY environment variable.'
      });
    }

    const systemInstructionText = ` You are Gemini Spark, an elite Media Buyer, Growth Hacker, and Senior Marketing Strategist Mentor.
Your role is to act as an expert mentor to the user, providing clear, actionable, and non-complex marketing advice.
You specialize in Meta Ads (Facebook & Instagram), TikTok Ads, Google Ads, E-commerce growth, Lead Generation, Copywriting, Funnel Optimization, and Conversion Rate Optimization (CRO).

Guidelines:
1. Speak directly, professionally, and encouragingly (support Arabic and English seamlessly based on user input).
2. Give practical, step-by-step guidance rather than vague theory.
3. Break down complex media buying concepts (CPA, ROAS, CPM, CBO/ABO, Custom Audiences, Retargeting) into easy-to-understand steps.
4. When diagnosing issues, analyze the 4 core pillars: Visual Hook, Ad Copy/Angles, Offer/Pricing, and Landing Page/Destination.
`;

    // Construct contents array with history and current prompt
    const contents = [];

    if (Array.isArray(history) && history.length > 0) {
      history.forEach((msg) => {
        if (msg && msg.text) {
          const role = msg.role === 'user' ? 'user' : 'model';
          contents.push({
            role: role,
            parts: [{ text: msg.text }]
          });
        }
      });
    }

    contents.push({
      role: 'user',
      parts: [{ text: prompt }]
    });

    const requestPayload = {
      systemInstruction: {
        parts: [{ text: systemInstructionText }]
      },
      contents: contents,
      generationConfig: {
        temperature: 0.7,
        topP: 0.95,
        maxOutputTokens: 2048
      }
    };

    // Call Gemini 2.5 Flash Endpoint with fallback to 1.5 Flash if needed
    let modelName = 'gemini-2.5-flash';
    let apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

    let apiResponse = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestPayload)
    });

    // Fallback if 2.5 model is not available for this key
    if (!apiResponse.ok && apiResponse.status === 404) {
      modelName = 'gemini-1.5-flash';
      apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
      apiResponse = await fetch(apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestPayload)
      });
    }

    if (!apiResponse.ok) {
      const errorData = await apiResponse.json().catch(() => ({}));
      return res.status(apiResponse.status).json({
        error: errorData.error?.message || `Gemini API error (${apiResponse.status})`,
        details: errorData
      });
    }

    const data = await apiResponse.json();
    const replyText =
      data.candidates?.[0]?.content?.parts?.[0]?.text ||
      'No response text generated by Gemini.';

    return res.status(200).json({
      success: true,
      model: modelName,
      reply: replyText,
      usage: data.usageMetadata || null
    });
  } catch (err) {
    console.error('Error in /api/chat:', err);
    return res.status(500).json({
      error: 'Internal server error processing chat request.',
      message: err.message
    });
  }
}
