import fs from 'fs';
import path from 'path';

export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization, x-api-key'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  try {
    const {
      businessType = 'General / E-commerce',
      budget = 'Medium',
      goal = 'Sales',
      platform = 'Meta Ads',
      apiKey: bodyApiKey
    } = req.body || {};

    const apiKey = bodyApiKey || req.headers['x-api-key'] || process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(401).json({
        error: 'Gemini API Key is required. Provide it in req.body.apiKey or set GEMINI_API_KEY environment variable.'
      });
    }

    // Attempt to load strategy library
    let strategies = [];
    try {
      const filePath = path.join(process.cwd(), 'public', 'strategies.json');
      if (fs.existsSync(filePath)) {
        const fileData = fs.readFileSync(filePath, 'utf-8');
        strategies = JSON.parse(fileData);
      }
    } catch (e) {
      console.warn('Could not read strategies.json, fallback to dynamic Gemini generation:', e.message);
    }

    const matchedStrategiesSummary = strategies.length > 0
      ? JSON.stringify(strategies.slice(0, 3), null, 2)
      : 'Default strategy framework';

    const systemPrompt = `You are a Senior Media Buyer and Growth Strategist AI Mentor.
Your task is to recommend a highly tailored, step-by-step advertising & marketing strategy based on the user's business inputs.

User Business Profile:
- Business/Product Type: ${businessType}
- Target Platform: ${platform}
- Budget Level: ${budget}
- Primary Business Goal: ${goal}

Available Strategy Frameworks Context:
${matchedStrategiesSummary}

Provide a comprehensive, easy-to-follow, structured strategy recommendation report in Arabic (or English if requested).
Structure the report cleanly as follows:
1. **Executive Strategy Summary**: Key concept, why this fits their specific business & budget.
2. **Phase 1 - Campaign Setup & Targeting**: Structure (CBO vs ABO), Ad sets, target audiences, and budget allocation.
3. **Phase 2 - Creative Angle & Ad Copy**: Suggested ad formats (Video Hook, Carousel, UGC), messaging angles, and offers.
4. **Phase 3 - Optimization & Scaling Rules**: How to scale winning ads (Vertical/Horizontal) and when to pause underperformers.
5. **Expected KPIs & Metrics Benchmark**: Target CPA, CTR, CPM, and ROAS.`;

    const requestPayload = {
      contents: [
        {
          role: 'user',
          parts: [{ text: `Generate a custom marketing strategy report for my business: ${businessType}, budget: ${budget}, goal: ${goal}, platform: ${platform}.` }]
        }
      ],
      systemInstruction: {
        parts: [{ text: systemPrompt }]
      },
      generationConfig: {
        temperature: 0.6,
        topP: 0.9,
        maxOutputTokens: 2048
      }
    };

    let modelName = 'gemini-2.5-flash';
    let apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

    let apiResponse = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestPayload)
    });

    if (!apiResponse.ok && apiResponse.status === 404) {
      modelName = 'gemini-1.5-flash';
      apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
      apiResponse = await fetch(apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestPayload)
      });
    }

    if (!apiResponse.ok) {
      const errorData = await apiResponse.json().catch(() => ({}));
      return res.status(apiResponse.status).json({
        error: errorData.error?.message || `Gemini API error (${apiResponse.status})`,
        details: errorData
      });
    }

    const data = await apiResponse.json();
    const strategyReport =
      data.candidates?.[0]?.content?.parts?.[0]?.text ||
      'No recommendation generated by Gemini.';

    return res.status(200).json({
      success: true,
      model: modelName,
      inputs: { businessType, budget, goal, platform },
      matchedStrategies: strategies.slice(0, 3),
      recommendationReport: strategyReport,
      usage: data.usageMetadata || null
    });
  } catch (err) {
    console.error('Error in /api/recommend:', err);
    return res.status(500).json({
      error: 'Internal server error processing recommendation request.',
      message: err.message
    });
  }
}
